version: "3.8"

services:
  postgres:
    hostname: postgres
    container_name: jen-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/20230728043352_initial.up.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    container_name: jen-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: anishsinha0128@gmail.com
      PGADMIN_DEFAULT_PASSWORD: anishsinha
    ports:
      - "8889:80"
    hostname: pgadmin
    depends_on:
      - postgres
  redis:
    hostname: redis
    container_name: jen-redis
    image: redis
    ports:
      - "6379:6379"
  redis-insight:
    hostname: redis-ui
    container_name: jen-redis-ui
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    depends_on:
      - redis
